"""Draft model for the Intent-Driven Project Orchestrator.

Stores user-facing Draft proposals that have been generated by the
Orchestrator Service but not yet approved by the user. After user
approval, AtomicCreator materializes the Draft into a real Group +
Agents + OKR + Tasks, then marks the Draft status='consumed'.

Idempotency: AtomicCreator uses draft.id as the idempotency key so
retries with the same draft_id produce identical downstream state.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Draft(Base):
    """A user-visible proposal awaiting approval before becoming a real project."""

    __tablename__ = "drafts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    user_message: Mapped[str] = mapped_column(nullable=False)
    intent_summary: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    draft_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    template_visibility: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="user_private"
    )
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="pending", index=True
    )
    # Values: pending / approved / rejected / expired / error / consumed
    error_detail: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Audit/cleanup field only - NOT used to drive any agent behavior.
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
